version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "final-python-thumbnail"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dag1qbzov3x"
s3_prefix = "final-python-thumbnail"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
