version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dag1qbzov3x"
s3_prefix = "sam-app2"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=\"sam-example-apigw-smat\""
image_repositories = []
