version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-sam-example-email"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dag1qbzov3x"
s3_prefix = "stack-sam-example-email"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MailAddress=\"matsuya@h01.itscom.net\" MailTableName=\"mailaddress\" BucketName=\"mailbody-smat710\""
image_repositories = []
