version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-face-rekognition"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dag1qbzov3x"
s3_prefix = "sam-face-rekognition"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Table=\"Faces\" Region=\"ap-northeast-1\""
image_repositories = []
