version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-sam-example-s3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dag1qbzov3x"
s3_prefix = "stack-sam-example-s3"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
