version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "news-schedule-sentiment"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17dag1qbzov3x"
s3_prefix = "news-schedule-sentiment"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Table=\"News\" Topic=\"Happy-News\" Region=\"ap-northeast-1\" NewsApiKey=\"sam-news-api-key\""
image_repositories = []
